#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec  5 16:02:38 2020

@author: ghiggi
"""
import matplotlib.pylab as plt
from matplotlib import animation

### blit = False 
fig = plt.figure()

plt.hold(True)
#We need to prime the pump, so to speak and create a quadmesh for plt to work with
plt.pcolormesh(X[0:1], Y[0:1], C[0:1])

anim = animation.FuncAnimation(fig, animate, frames = range(2,155), blit = False)

plt.show()
plt.hold(False)

def animate( self, i):
    plt.title('Ray: %.2f'%i)
    #This is where new data is inserted into the plot.
    plt.pcolormesh(X[i-2:i], Y[i-2:i], C[i-2:i])
    

## blit = True 

fig = plt.figure()
plt.hold(True)
#We need to prime the pump, so to speak and create a quadmesh for plt to work with
pcm = plt.pcolormesh(X[0:1], Y[0:1], C[0:1])
pcm.set_array(new_cdata)

anim = animation.FuncAnimation(fig, animate, frames = range(2,155), blit = True)

plt.show()
plt.hold(False)

def animate1( self, i):
    plt.title('Ray: %.2f'%i)
    #This is where new data is inserted into the plot.
    pcm = plt.pcolormesh(X[i-2:i], Y[i-2:i], C[i-2:i])
    # Return pcm as an element of a 1-element tuple
    return pcm, 